### 
  GET http://localhost:5161

###

# there are searching value is apple, if we find anything we will return it
GET http://localhost:5161/api/categories

###

GET http://localhost:5161/api/categories/8ec90bd0-9947-4f9c-9bfa-95888cc8b7ee

 
###

POST http://localhost:5161/api/categories
Content-Type: application/json

{
    "name": "actttt",
  "description": "Electronices is most valueable parts for honda and cars"

}

###

  DELETE http://localhost:5161/api/categories/8e24e3af-518c-4a7f-854b-b8156352d73d


###
  PUT http://localhost:5161/api/categories/b2997bee-1a8a-4be8-86d6-60a2dee3abeb
  Content-Type: application/json

  {
    "name": "Alu phone",
    "description": "Electronices is most valueable parts for honda and cars"
  }

 
 