### 
  GET http://localhost:5161

###

# there are searching value is apple, if we find anything we will return it
GET http://localhost:5161/api/categories

###


POST http://localhost:5161/api/categories
Content-Type: application/json

{
    "name": "aaaxxxxxxaA",
  "description": "Electronices is most valueable parts for honda and cars"

}

###

  DELETE http://localhost:5161/api/categories/369e95f1-9e05-493a-8012-73fcb7caae41


###
  PUT http://localhost:5161/api/categories/a7a4c619-b21d-4838-91a8-bd73c7c5fcce
  Content-Type: application/json

  {
    "name": "Alu phone",
    "description": "Electronices is most valueable parts for honda and cars"
  }

 
 